#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PoemGamesApp.Resource", IsApplication=true)]

namespace PoemGamesApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int bn1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int bn2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int bn3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int bn4 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int bn5 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int bn6 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int bn7 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int bn8 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int bn9 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int btnDelete = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int btnShow = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int gridLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int txtLine = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int txtRes = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int txtSuccess = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
